#!/usr/bin/env bash
# Bootstrap Environment Activation Script
# Generated by: bootstrap-repo-cli
# Purpose: Activate the development environment created by the bootstrapper
#
# Usage:
#   source .bootstrap/activate.sh
#   # OR
#   . .bootstrap/activate.sh

# Exit if not being sourced
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    echo "Error: This script must be sourced, not executed directly"
    echo "Usage: source ${BASH_SOURCE[0]}"
    exit 1
fi

# Activate Python virtual environment
if [ -f "/home/runner/work/RFC-Shared-Agent-Scaffolding/RFC-Shared-Agent-Scaffolding/.venv/bin/activate" ]; then
    source "/home/runner/work/RFC-Shared-Agent-Scaffolding/RFC-Shared-Agent-Scaffolding/.venv/bin/activate"
    echo "✓ Python virtual environment activated"
else
    echo "⚠ Warning: Virtual environment not found at /home/runner/work/RFC-Shared-Agent-Scaffolding/RFC-Shared-Agent-Scaffolding/.venv"
fi

# Add Perl tools to PATH and set PERL5LIB
export PATH="/home/runner/perl5/bin:$PATH"
export PERL5LIB="/home/runner/perl5/lib/perl5:${PERL5LIB:+:$PERL5LIB}"
echo "✓ Perl environment configured"

# Mark as activated
export BOOTSTRAP_ACTIVATED=1

echo ""
echo "✅ Bootstrap environment activated!"
echo ""
echo "To deactivate, run: deactivate"
