# File: multi-phase-form.yml
#
# Purpose: GitHub issue form template for tracking multi-phase feature
# implementations. Provides structured fields for Future Work (FW) items
# from docs/FUTURE-WORK.md that require multiple PRs across several phases.
#
# Usage:
# - Users create new issues via this template when starting multi-phase work
# - Template appears in GitHub's "New Issue" menu
# - Form validates required fields (FW reference, summary, phases)
#
# Inputs:
# - FW Reference: ID from FUTURE-WORK.md (format: FW-XXX)
# - Summary: High-level description of the feature
# - Phase Breakdown: List of phases with goals
# - PR Chain: Checklist of PRs (updated as work progresses)
#
# Outputs:
# - Creates GitHub issue with "epic" and "tracking" labels
# - Assigns issue to @m1ndn1nj4
# - Structures issue body with form fields
#
# Notes:
# - This is a GitHub Issue Form YAML template, not executable code
# - Standard phase count is 3 (adjustable per feature complexity)
# - PR chain checklist enables progress tracking in issue
# - See: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

name: Multi-Phase Feature Implementation
description: Track progress across multi-PR phased work for a Future Work (FW) item from docs/FUTURE-WORK.md
title: "EPIC: Multi-Phase Implementation for FW-XXX"
labels: ["epic", "tracking"]
assignees:
  - m1ndn1nj4
body:
  - type: input
    id: fw-id
    attributes:
      label: FW Reference
      placeholder: e.g. FW-002
      description: Future Work ID from `docs/FUTURE-WORK.md` (format FW-XXX)
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What this future work item is trying to implement
      placeholder: Describe the feature across all phases...
    validations:
      required: true

  - type: textarea
    id: phases
    attributes:
      label: Phase Breakdown
      description: Define each phase and its goal (3 is standard)
      placeholder: |
        - Phase 1: Command existence check
        - Phase 2: Repo and dependency validation
        - Phase 3: Conformance test coverage
    validations:
      required: true

  - type: textarea
    id: pr-chain
    attributes:
      label: PR Chain (fill or update as work progresses)
      placeholder: |
        - [ ] PR1: `copilot/fwxxx-phase1` → main
        - [ ] PR2: `copilot/fwxxx-phase2` → main
        - [ ] PR3: `copilot/fwxxx-phase3` → main
