//! # Environment Activation Module
//!
//! # Purpose
//!
//! Generates activation scripts and commands to help users activate the bootstrapped
//! environment in their shell. Since the Rust binary cannot modify the parent shell's
//! environment directly (OS process isolation), this module provides safe, explicit,
//! auditable mechanisms for environment activation.
//!
//! # Examples
//!
//! Generate activation script:
//! ```no_run
//! use bootstrap_v2::activate::write_activation_script;
//! use std::path::PathBuf;
//!
//! let repo_root = PathBuf::from("/path/to/repo");
//! let venv_path = repo_root.join(".venv");
//! write_activation_script(&repo_root, &venv_path).expect("Failed to write activation script");
//! ```

use anyhow::Result;
use std::fs;
use std::path::Path;

/// Write a sourceable activation script to the repository
///
/// Creates `.bootstrap/activate.sh` that users can source to activate the environment:
/// ```bash
/// source .bootstrap/activate.sh
/// ```
pub fn write_activation_script(repo_root: &Path, venv_path: &Path) -> Result<()> {
    let bootstrap_dir = repo_root.join(".bootstrap");
    fs::create_dir_all(&bootstrap_dir)?;

    let activate_script = bootstrap_dir.join("activate.sh");

    let home = std::env::var("HOME").unwrap_or_else(|_| "/home/runner".to_string());
    let perl_bin = format!("{}/perl5/bin", home);
    let perl_lib = format!("{}/perl5/lib/perl5", home);

    let script_content = format!(
        r#"#!/usr/bin/env bash
# Bootstrap Environment Activation Script
# Generated by: bootstrap-repo-cli
# Purpose: Activate the development environment created by the bootstrapper
#
# Usage:
#   source .bootstrap/activate.sh
#   # OR
#   . .bootstrap/activate.sh

# Exit if not being sourced
if [ "${{BASH_SOURCE[0]}}" = "${{0}}" ]; then
    echo "Error: This script must be sourced, not executed directly"
    echo "Usage: source ${{BASH_SOURCE[0]}}"
    exit 1
fi

# Activate Python virtual environment
if [ -f "{venv}/bin/activate" ]; then
    source "{venv}/bin/activate"
    echo "✓ Python virtual environment activated"
else
    echo "⚠ Warning: Virtual environment not found at {venv}"
fi

# Add Perl tools to PATH and set PERL5LIB
export PATH="{perl_bin}:$PATH"
export PERL5LIB="{perl_lib}:${{PERL5LIB:+:$PERL5LIB}}"
echo "✓ Perl environment configured"

# Mark as activated
export BOOTSTRAP_ACTIVATED=1

echo ""
echo "✅ Bootstrap environment activated!"
echo ""
echo "To deactivate, run: deactivate"
"#,
        venv = venv_path.display(),
        perl_bin = perl_bin,
        perl_lib = perl_lib,
    );

    fs::write(&activate_script, script_content)?;

    // Make script executable
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&activate_script)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&activate_script, perms)?;
    }

    Ok(())
}

/// Generate shell commands for eval (print to stdout)
///
/// Emits shell commands that can be evaluated to activate the environment:
/// ```bash
/// eval "$(bootstrap-repo-cli install --profile dev --emit-env-commands)"
/// ```
pub fn emit_env_commands(_repo_root: &Path, venv_path: &Path) {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/home/runner".to_string());
    let perl_home = format!("{}/perl5", home);
    let perl_bin = format!("{}/bin", perl_home);
    let perl_lib = format!("{}/lib/perl5", perl_home);

    // Emit commands for shell evaluation
    println!("# Bootstrap environment activation commands");
    println!("# Activate Python venv");
    println!("source {}/bin/activate", venv_path.display());
    println!("# Configure Perl environment");
    println!("export PATH=\"{}:$PATH\"", perl_bin);
    println!("export PERL5LIB=\"{}:${{PERL5LIB}}\"", perl_lib);
    println!("export BOOTSTRAP_ACTIVATED=1");
}

/// Write environment variables to GitHub Actions environment file
///
/// Persists environment variables across GitHub Actions steps by writing to $GITHUB_ENV:
/// ```yaml
/// - name: Bootstrap toolchain
///   run: ./rust/target/release/bootstrap-repo-cli install --profile ci --github-env
/// ```
pub fn write_github_env(_repo_root: &Path, venv_path: &Path) -> Result<()> {
    let github_env_path = std::env::var("GITHUB_ENV")
        .map_err(|_| anyhow::anyhow!("GITHUB_ENV not set - not running in GitHub Actions"))?;

    let home = std::env::var("HOME").unwrap_or_else(|_| "/home/runner".to_string());
    let perl_home = format!("{}/perl5", home);
    let perl_bin = format!("{}/bin", perl_home);
    let perl_lib = format!("{}/lib/perl5", perl_home);

    let venv_bin = venv_path.join("bin");
    let current_path = std::env::var("PATH").unwrap_or_default();

    // Build new PATH with venv and Perl bins
    let new_path = format!("{}:{}:{}", perl_bin, venv_bin.display(), current_path);

    // Append to GITHUB_ENV file
    let mut env_content = String::new();
    env_content.push_str(&format!("PATH={}\n", new_path));
    env_content.push_str(&format!("PERL5LIB={}\n", perl_lib));
    env_content.push_str(&format!("VIRTUAL_ENV={}\n", venv_path.display()));
    env_content.push_str("BOOTSTRAP_ACTIVATED=1\n");

    use std::fs::OpenOptions;
    use std::io::Write;

    let mut file = OpenOptions::new()
        .append(true)
        .create(true)
        .open(&github_env_path)?;

    file.write_all(env_content.as_bytes())?;

    println!("✓ Environment variables written to $GITHUB_ENV");
    println!("  PATH, PERL5LIB, VIRTUAL_ENV, and BOOTSTRAP_ACTIVATED set for subsequent steps");

    Ok(())
}

/// Print activation instructions to the user
pub fn print_activation_instructions(repo_root: &Path, ci_mode: bool) {
    if ci_mode {
        println!("\n📋 CI Environment Activation:");
        println!(
            "   For GitHub Actions, use --github-env flag to persist environment across steps"
        );
        println!("   For other CI systems, source .bootstrap/activate.sh in subsequent commands");
    } else {
        println!("\n📋 To activate the environment in your shell:");
        println!("   source .bootstrap/activate.sh");
        println!("\n   OR use eval:");
        println!("   eval \"$(./rust/target/release/bootstrap-repo-cli install --profile dev 2>/dev/null | grep '^export\\|^source')\"");
        println!("\n   The activation script is located at:");
        println!("   {}", repo_root.join(".bootstrap/activate.sh").display());
    }
}
